name: CI 

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      - uses: actions/checkout@v2
      
      - name: Install dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install ci
      - run: npm ci
      - name: Run tests
      - run: npm test
